spring.application.name=seminovos-assistant
gemini.api.key=Gemeni-API-Key
gemini.model=gemini-2.5-flash
server.port=8080
logging.level.dev.langchain4j=DEBUG
logging.level.dev.langchain4j.service=DEBUG
logging.level.dev.langchain4j.model=DEBUG
logging.level.root=INFO